#!/usr/bin/env python3
"""
Demo Mode Script
Loads demo configuration for showcasing PartnerOS.

Usage:
    python scripts/demo_mode.py              # Show demo info
    python scripts/demo_mode.py --activate  # Activate demo mode
    python scripts/demo_mode.py --deactivate # Deactivate demo mode
"""

import os
import sys
import yaml
import shutil
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
DEMO_CONFIG = REPO_ROOT / "examples" / "demo-company" / "demo-config.yaml"
COMPANY_CONFIG = REPO_ROOT / ".company-config" / "customize.yaml"
BACKUP_SUFFIX = ".backup"


def load_demo_config():
    """Load demo configuration."""
    if not DEMO_CONFIG.exists():
        print(f"Error: Demo config not found: {DEMO_CONFIG}")
        return None

    with open(DEMO_CONFIG, "r") as f:
        return yaml.safe_load(f)


def show_demo_info():
    """Show demo configuration info."""
    config = load_demo_config()
    if not config:
        return

    print("\n" + "=" * 60)
    print("  PartnerOS Demo Mode")
    print("=" * 60)

    if "company" in config:
        print(f"\nDemo Company: {config['company']['name']}")
        print(f"Website: {config['company']['website']}")

    if "demo" in config:
        print(f"\nCompany Type: {config['demo'].get('company_type', 'N/A')}")
        print(f"Target Market: {config['demo'].get('target_market', 'N/A')}")

        tiers = config["demo"].get("partner_tiers", {})
        print(f"\nCurrent Partners: {config['demo'].get('current_partners', 0)}")
        print(f"  Gold: {tiers.get('gold', 0)}")
        print(f"  Silver: {tiers.get('silver', 0)}")
        print(f"  Bronze: {tiers.get('bronze', 0)}")

    if "partners" in config:
        print(f"\nSample Partners:")
        for partner in config["partners"][:3]:
            print(f"  - {partner['name']} ({partner['tier']})")

    if "notes" in config:
        print(f"\nDemo Notes:")
        print(config["notes"])

    print("=" * 60 + "\n")


def activate_demo_mode():
    """Activate demo mode (load demo config)."""
    if not DEMO_CONFIG.exists():
        print("Error: Demo config not found")
        return False

    # Backup current config if exists
    if COMPANY_CONFIG.exists():
        backup = COMPANY_CONFIG.with_suffix(BACKUP_SUFFIX)
        shutil.copy(COMPANY_CONFIG, backup)
        print(f"Backed up current config to: {backup}")

    # Copy demo config to active config
    demo_vars = {}
    config = load_demo_config()

    if "company" in config:
        demo_vars["company_name"] = config["company"]["name"]
        demo_vars["company_website"] = config["company"]["website"]
    if "contact" in config:
        demo_vars["contact_name"] = config["contact"]["name"]
        demo_vars["contact_email"] = config["contact"]["email"]
        demo_vars["primary_contact_role"] = config["contact"]["role"]
    if "branding" in config:
        demo_vars["logo_url"] = config["branding"].get("logo_url", "")
        demo_vars["brand_color"] = config["branding"].get("brand_color", "#6366F1")

    # Create active config
    COMPANY_CONFIG.parent.mkdir(exist_ok=True)

    config_content = f"""# PartnerOS Demo Configuration
# Generated by demo_mode.py
# DO NOT USE IN PRODUCTION

company:
  name: "{demo_vars.get("company_name", "Demo Company")}"
  website: "{demo_vars.get("company_website", "https://demo.com")}"
  
contact:
  name: "{demo_vars.get("contact_name", "Demo User")}"
  email: "{demo_vars.get("contact_email", "demo@demo.com")}"
  role: "{demo_vars.get("primary_contact_role", "Partner Manager")}"
  
branding:
  logo_url: "{demo_vars.get("logo_url", "")}"
  brand_color: "{demo_vars.get("brand_color", "#6366F1")}"
  
variables:
  company_name: "{demo_vars.get("company_name", "Demo Company")}"
  company_website: "{demo_vars.get("company_website", "https://demo.com")}"
  contact_name: "{demo_vars.get("contact_name", "Demo User")}"
  contact_email: "{demo_vars.get("contact_email", "demo@demo.com")}"
  logo_url: "{demo_vars.get("logo_url", "")}"
  brand_color: "{demo_vars.get("brand_color", "#6366F1")}"
  primary_contact_role: "{demo_vars.get("primary_contact_role", "Partner Manager")}"
"""

    with open(COMPANY_CONFIG, "w") as f:
        f.write(config_content)

    print(f"✓ Demo mode activated: {COMPANY_CONFIG}")
    print("\nUse templates with demo data:")
    print(
        "  python scripts/fill_template.py --template docs/recruitment/01-email-sequence.md"
    )

    return True


def deactivate_demo_mode():
    """Deactivate demo mode (restore original config)."""
    backup = COMPANY_CONFIG.with_suffix(BACKUP_SUFFIX)

    if backup.exists():
        shutil.copy(backup, COMPANY_CONFIG)
        backup.unlink()
        print(f"✓ Restored original config from: {backup}")
    else:
        if COMPANY_CONFIG.exists():
            COMPANY_CONFIG.unlink()
            print("✓ Removed demo config")
        else:
            print("No config to remove")

    return True


def main():
    import argparse

    parser = argparse.ArgumentParser(description="PartnerOS Demo Mode")
    parser.add_argument("--activate", action="store_true", help="Activate demo mode")
    parser.add_argument(
        "--deactivate", action="store_true", help="Deactivate demo mode"
    )
    parser.add_argument("--info", action="store_true", help="Show demo info")

    args = parser.parse_args()

    if args.activate:
        activate_demo_mode()
    elif args.deactivate:
        deactivate_demo_mode()
    elif args.info:
        show_demo_info()
    else:
        # Default: show info
        show_demo_info()


if __name__ == "__main__":
    main()
