#!/usr/bin/env python3
"""
generate_report.py - Auto-generate monthly partner reports from saved state.

Usage:
    python scripts/generate_report.py                      # Report for all partners
    python scripts/generate_report.py --partner acme-corp  # Single partner
    python scripts/generate_report.py --output reports/    # Custom output dir
    python scripts/generate_report.py --format md          # Markdown (default)
"""

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
STATE_DIR = REPO_ROOT / "scripts" / "partner_agent" / "state"


def load_partner(slug_or_name: str) -> dict:
    """Load a single partner's state by slug or display name."""
    candidate = STATE_DIR / slug_or_name / "metadata.json"
    if candidate.exists():
        with open(candidate) as f:
            return json.load(f)
    # Fuzzy match on name
    for d in STATE_DIR.iterdir():
        meta = d / "metadata.json"
        if meta.exists():
            with open(meta) as f:
                data = json.load(f)
            if data.get("name", "").lower() == slug_or_name.lower():
                return data
    raise FileNotFoundError(f"Partner not found: {slug_or_name}")


def load_all_partners() -> list:
    """Load all partner state files."""
    partners = []
    if not STATE_DIR.exists():
        return partners
    for d in sorted(STATE_DIR.iterdir()):
        meta = d / "metadata.json"
        if meta.exists():
            with open(meta) as f:
                partners.append(json.load(f))
    return partners


def health_badge(score) -> str:
    if score is None:
        return "⬜ Not assessed"
    if score >= 80:
        return f"🟢 {score}/100"
    if score >= 50:
        return f"🟡 {score}/100"
    return f"🔴 {score}/100"


def format_partner_report(p: dict, generated_at: str) -> str:
    tier = p.get("tier") or "Unclassified"
    vertical = p.get("vertical") or "Unknown"
    rm = p.get("rm") or "Unassigned"
    health = health_badge(p.get("health_score"))
    created = (p.get("created") or "")[:10]

    # Playbook summary
    playbooks = p.get("playbooks", {})
    completed = [k for k, v in playbooks.items() if v.get("completed")]
    in_progress = [k for k, v in playbooks.items() if not v.get("completed")]

    pb_lines = []
    for name, data in playbooks.items():
        if data.get("completed"):
            done_at = (data.get("completed_at") or "")[:10]
            pb_lines.append(f"  - ✅ **{name}** — completed {done_at}")
        else:
            step = data.get("current_step", 0)
            pb_lines.append(f"  - 🔄 **{name}** — step {step} in progress")

    playbook_section = "\n".join(pb_lines) if pb_lines else "  - No playbooks started"

    # Milestones
    milestones = p.get("milestones", [])
    milestone_lines = []
    for m in milestones[-5:]:  # last 5
        ts = (m.get("ts") or "")[:10]
        milestone_lines.append(f"  - {ts}: {m['name']}")
    milestone_section = "\n".join(milestone_lines) if milestone_lines else "  - None recorded"

    # Recent notes
    notes = p.get("notes", [])
    note_lines = []
    for n in notes[-5:]:  # last 5
        ts = (n.get("ts") or "")[:10]
        note_lines.append(f"  - **{ts}**: {n['text']}")
    notes_section = "\n".join(note_lines) if note_lines else "  - No notes"

    return f"""## {p['name']}

| Field | Value |
|-------|-------|
| Tier | {tier} |
| Vertical | {vertical} |
| Health | {health} |
| Relationship Manager | {rm} |
| Partner Since | {created} |

### Playbook Progress

{playbook_section}

### Milestones

{milestone_section}

### Notes

{notes_section}

---
"""


def generate_report(partners: list, generated_at: str) -> str:
    summary_rows = []
    for p in partners:
        tier = p.get("tier") or "—"
        health = p.get("health_score")
        health_str = f"{health}/100" if health is not None else "—"
        completed = sum(1 for v in p.get("playbooks", {}).values() if v.get("completed"))
        summary_rows.append(f"| {p['name']} | {tier} | {health_str} | {completed} |")

    summary_table = "\n".join(summary_rows) if summary_rows else "| — | — | — | — |"

    partner_sections = "\n".join(format_partner_report(p, generated_at) for p in partners)

    return f"""# PartnerOS Monthly Report

**Generated:** {generated_at}
**Partners tracked:** {len(partners)}

---

## Executive Summary

| Partner | Tier | Health | Playbooks Completed |
|---------|------|--------|---------------------|
{summary_table}

---

## Partner Details

{partner_sections}
*Report generated by PartnerOS — https://github.com/danieloleary/PartnerOS*
"""


def main():
    parser = argparse.ArgumentParser(description="Generate monthly partner reports from PartnerOS state")
    parser.add_argument("--partner", "-p", help="Single partner slug or name (default: all)")
    parser.add_argument("--output", "-o", help="Output directory (default: stdout)")
    parser.add_argument("--state-dir", help="Override state directory path")
    args = parser.parse_args()

    global STATE_DIR
    if args.state_dir:
        STATE_DIR = Path(args.state_dir)

    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")

    if args.partner:
        try:
            partners = [load_partner(args.partner)]
        except FileNotFoundError as e:
            print(f"Error: {e}", file=sys.stderr)
            sys.exit(1)
    else:
        partners = load_all_partners()
        if not partners:
            print("No partner state found. Run a playbook first.", file=sys.stderr)
            sys.exit(0)

    report = generate_report(partners, generated_at)

    if args.output:
        out_dir = Path(args.output)
        out_dir.mkdir(parents=True, exist_ok=True)
        filename = f"partner-report-{datetime.now().strftime('%Y-%m')}.md"
        out_path = out_dir / filename
        out_path.write_text(report)
        print(f"Report written to {out_path}")
    else:
        print(report)


if __name__ == "__main__":
    main()
