#!/usr/bin/env python3
"""
Company Onboarding Script
Helps new companies set up PartnerOS for their use.

Usage:
    python scripts/onboard.py
    python scripts/onboard.py --non-interactive
"""

import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
CONFIG_DIR = REPO_ROOT / ".company-config"
CONFIG_FILE = CONFIG_DIR / "customize.yaml"

VARIABLES = {
    "company_name": "Your Company Name",
    "company_website": "https://yourcompany.com",
    "contact_name": "Partner Manager Name",
    "contact_email": "partners@yourcompany.com",
    "logo_url": "",
    "brand_color": "#3B82F6",
    "primary_contact_role": "Partner Manager",
}


def print_header():
    print("\n" + "=" * 60)
    print("  PartnerOS Company Onboarding")
    print("  Set up PartnerOS for your company")
    print("=" * 60 + "\n")


def get_input(prompt, default="", required=True):
    """Get input from user with default."""
    if default:
        response = input(f"{prompt} [{default}]: ").strip()
        return response if response else default
    else:
        while True:
            response = input(f"{prompt}: ").strip()
            if response or not required:
                return response
            print("  This field is required. Please enter a value.")


def get_company_info():
    """Collect company information."""
    print("Let's set up PartnerOS for your company!\n")
    print("Press Enter to accept the default value in brackets.\n")

    info = {}

    info["company_name"] = get_input("What is your company name", "Acme Corporation")

    info["company_website"] = get_input(
        "What is your company website", "https://example.com"
    )

    info["contact_name"] = get_input("Who is the main partner contact", "John Smith")

    info["contact_email"] = get_input("What is their email", "partners@example.com")

    info["primary_contact_role"] = get_input("What is their role", "Partner Manager")

    info["logo_url"] = get_input(
        "Logo URL (optional, press Enter to skip)", "", required=False
    )

    info["brand_color"] = get_input("Brand color (hex code)", "#3B82F6")

    return info


def create_config_file(info):
    """Create the customization config file."""
    CONFIG_DIR.mkdir(exist_ok=True)

    config_content = f"""# PartnerOS Company Configuration
# Generated by scripts/onboard.py
# 
# This file contains your company-specific settings.
# Variables in templates will be replaced with these values.
#
# DO NOT COMMIT THIS FILE if it contains sensitive info.
# Add to .gitignore if needed.

company:
  name: "{info["company_name"]}"
  website: "{info["company_website"]}"
  
contact:
  name: "{info["contact_name"]}"
  email: "{info["contact_email"]}"
  role: "{info["primary_contact_role"]}"
  
branding:
  logo_url: "{info["logo_url"]}"
  brand_color: "{info["brand_color"]}"
  
# Template variables (these are replaced in templates)
variables:
  company_name: "{info["company_name"]}"
  company_website: "{info["company_website"]}"
  contact_name: "{info["contact_name"]}"
  contact_email: "{info["contact_email"]}"
  logo_url: "{info["logo_url"]}"
  brand_color: "{info["brand_color"]}"
  primary_contact_role: "{info["primary_contact_role"]}"
"""

    with open(CONFIG_FILE, "w") as f:
        f.write(config_content)

    print(f"\n✓ Created: {CONFIG_FILE}")
    return CONFIG_FILE


def show_next_steps():
    """Show user what to do next."""
    print("\n" + "=" * 60)
    print("  Setup Complete!")
    print("=" * 60)
    print("""
Next steps:

1. Review your config:
   cat .company-config/customize.yaml

2. Browse templates:
   - Strategy: docs/strategy/
   - Recruitment: docs/recruitment/
   - Enablement: docs/enablement/
   - Legal: docs/legal/
   - Finance: docs/finance/

3. Use template variables:
   {{company_name}} will be replaced with your company name
   {{contact_name}} will be replaced with your contact

4. Generate a filled template:
   python scripts/fill_template.py --template docs/recruitment/01-email-sequence.md

5. For help, see:
   docs/getting-started/quick-start.md
""")

    print("=" * 60 + "\n")


def main():
    print_header()

    # Check if already configured
    if CONFIG_FILE.exists():
        response = (
            input(f"PartnerOS is already configured. Reconfigure? (y/N): ")
            .strip()
            .lower()
        )
        if response != "y":
            print("\nKeeping existing configuration.")
            show_next_steps()
            return

    # Get company info
    info = get_company_info()

    # Create config
    create_config_file(info)

    # Show next steps
    show_next_steps()


if __name__ == "__main__":
    main()
